# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
    build:
        docker:
            - image: circleci/php:7.1.13-apache-browsers
        working_directory: ~/sandbox

        steps:
            - checkout

            - run:
                name: Ubuntu
                command: sudo apt install uuid-dev

            - run:
                name: PHP
                command: |
                    sudo pecl channel-update pecl.php.net
                    yes | sudo pecl install uuid
                    #sudo docker-php-ext-install pdo pdo_mysql uuid
